import logging
import os
from datetime import datetime
import config
from kis_api import KisApi
import ai_analyst
import market_schedule

logging.basicConfig(level=logging.INFO)

def main():
    """Generates a market briefing."""
    logging.info("Starting Briefing Module...")
    kis = KisApi()
    
    # 1. Get Portfolio Status
    holdings, balance = kis.check_balance()
    
    # Simplified summary for AI
    portfolio_summary = {
        "total_balance_krw": balance.get("total_eval", 0),
        "holdings": []
    }
    
    for h in holdings:
        portfolio_summary["holdings"].append({
            "name": h["prdt_name"],
            "qty": h["hldg_qty"],
            "yield": h["evlu_pfls_rt"] + "%"
        })
        
    # 2. Determine Market Type for Briefing
    # Logic: If it's morning (KST 08~09), brief on US close/KR open.
    # If it's evening (KST 15~16), brief on KR close.
    # Currently running on UTC via GitHub Actions, so time check might be tricky.
    # Instead, we just generate for configured markets.
    
    market_type = "GLOBAL"
    if config.MARKET_TYPE == "DOMESTIC": 
        if not market_schedule.is_kr_market_open():
            logging.info("Skipping Briefing: Domest market Closed.")
            return
        market_type = "KR"
    elif config.MARKET_TYPE == "US": 
        if not market_schedule.is_us_market_open():
            logging.info("Skipping Briefing: US market Closed.")
            return
        market_type = "US"
    
    logging.info("Generating Briefing...")
    briefing_text = ai_analyst.generate_briefing(market_type, portfolio_summary)
    
    # 3. Save Briefing
    today = datetime.now().strftime("%Y-%m-%d")
    report_dir = os.path.join("reports", today)
    os.makedirs(report_dir, exist_ok=True)
    
    filename = f"briefing_{datetime.now().strftime('%H%M')}.md"
    file_path = os.path.join(report_dir, filename)
    
    with open(file_path, "w", encoding='utf-8') as f:
        f.write(f"# 📢 Market Briefing ({today})\n\n")
        f.write(briefing_text)
        
    logging.info(f"Briefing saved to {file_path}")
    
    # 4. Discord Notification
    import discord_notifier
    
    # Add a nice header based on market type
    header_title = "🌅 **장 시작 모닝 브리핑**" if market_type == "KR" else "🌙 **마감 시황 브리핑**"
    if market_type == "US": header_title = "🇺🇸 **미국 시장 브리핑**"
    
    discord_msg = f"{header_title}\n\n{briefing_text[:1900]}\n\n💡 _Generated by AI Analyst_"
    discord_notifier.send_message(discord_msg, type="briefing")

if __name__ == "__main__":
    main()
