import requests
import config
import logging

def send_message(message, type="trading"):
    """
    Send a message to the configured Discord Webhook.
    type: "trading" or "briefing"
    """
    if type == "briefing":
        url = config.DISCORD_WEBHOOK_BRIEFING
    else:
        url = config.DISCORD_WEBHOOK_TRADING
        
    # Fallback: If specific url missing, try the other, or fail
    if not url:
        if type == "trading" and config.DISCORD_WEBHOOK_BRIEFING: url = config.DISCORD_WEBHOOK_BRIEFING
        elif type == "briefing" and config.DISCORD_WEBHOOK_TRADING: url = config.DISCORD_WEBHOOK_TRADING
    
    if not url:
        logging.warning(f"Discord Webhook URL not set for {type}. Skipping.")
        return False
        
    payload = {
        "content": message
    }
    
    try:
        response = requests.post(url, json=payload, timeout=5)
        response.raise_for_status()
        return True
    except Exception as e:
        logging.error(f"Failed to send Discord message: {e}")
        return False

if __name__ == "__main__":
    # Test with realistic dummy data
    print("Sending Dummy Trading Report...")
    dummy_msg_trading = (
        "📊 **[2024-03-15] 데일리 트레이딩 리포트 (모의투자)** 📊\n\n"
        "**✅ 체결 내역**\n"
        "> 🔴 매수 **삼성전자**\n"
        "> `사유` AI: 긍정적 실적 전망 및 외국인 수급 유입\n\n"
        "> 🔵 매도 **TSLA**\n"
        "> `사유` RSI 과매수 구간 진입으로 인한 차익 실현\n\n"
        "\n👉 [상세 리포트 확인하기](https://github.com/Minwoo/korea_investment/actions)"
    )
    send_message(dummy_msg_trading, type="trading")
    
    print("Sending Dummy Briefing...")
    dummy_msg_briefing = (
        "🌅 **장 시작 모닝 브리핑 (모의투자)**\n\n"
        "**1. 시장 동향**\n"
        "간밤 뉴욕 증시는 CPI 둔화 영향으로 나스닥이 +1.5% 급등했습니다. 반도체 섹터 강세가 지속되고 있습니다.\n\n"
        "**2. 포트폴리오 점검**\n"
        "현재 수익률은 +3.2%입니다. 삼성전자의 상승세가 기대되나, 테슬라는 변동성에 유의해야 합니다.\n\n"
        "💡 _Generated by AI Analyst_"
    )
    send_message(dummy_msg_briefing, type="briefing")
    print("Done! Check your Discord channels.")
